import { useMemo } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/Card";
import { PredictionCard, RiskMatrix } from "@/components/dashboard/PredictionCard";
import { SimulatedBadge } from "@/components/ui/Misc";
import { LoadingState } from "@/components/ui/Misc";
import { usePredictions } from "@/hooks/useDrainageData";

export default function PredictionsPage() {
  const { predictions, loading } = usePredictions();

  const counts = useMemo(() => {
    const c = { low: 0, medium: 0, high: 0, critical: 0 };
    predictions.forEach((p) => c[p.risk]++);
    return c;
  }, [predictions]);

  const highlighted = predictions.slice(0, 6);

  return (
    <AppShell title="AI Drainage Intelligence" subtitle="Blockage risk prediction — future ML integration point">
      <div className="space-y-5">
        <Card className="border-dashed p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <p className="text-sm font-medium text-[var(--color-text-0)]">This page consumes a future ML API</p>
              <p className="mt-1 max-w-xl text-xs text-[var(--color-text-2)]">
                Blockage predictions shown here are generated by <span className="mono">MockMlAdapter</span>. Once a real model exists,
                swap it for <span className="mono">ApiMlAdapter</span> behind <span className="mono">POST /api/ml/predict</span> — no UI changes required.
              </p>
            </div>
            <SimulatedBadge />
          </div>
        </Card>

        {loading ? (
          <LoadingState rows={4} />
        ) : (
          <>
            <Card>
              <CardHeader><CardTitle>Risk matrix</CardTitle></CardHeader>
              <CardContent><RiskMatrix counts={counts} /></CardContent>
            </Card>

            <div>
              <h3 className="mb-3 text-sm font-semibold text-[var(--color-text-0)]">Highest-priority predictions</h3>
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {highlighted.map((p) => (
                  <PredictionCard key={p.nodeId} prediction={p} />
                ))}
              </div>
            </div>
          </>
        )}
      </div>
    </AppShell>
  );
}
